
public enum SoundCategory
{
    Music,
    SFX,
    Ambient,
    UI
}


public enum MusicType {
    LEVEL_MUSIC
}

public enum SFXType {
    MINED_COMPLETE,
    RESOURCE_BOUNCE,
    FLOOR_BOUNCE,
    HEADBUTT,
    COMBO_FAIL,
    FIRE_DAMAGE,
    PUSH_DAMAGE,
    RECIEVE_DAMAGE,
    ENEMY,
    SUPPORT_BLOCK,
    OPEN_CHEST,
    COLLECT_CHEST,
    DISCOVER_BP,
    UNLOCK_GATE,
    UNLOCK_DOOR,
    SWITCH_PRESS,
    TIMER_ON,
    TIMER_10S,
    COLLECT_KEY,
    PROJECTILE_IMPACT,
    GET_STUNN,
    HB_EXTLARGE_POTION,
    HB_LARGE_POTION,
    HB_MEDIUM_POTION,
    HB_SMALL_POTION,
    HP_EXTLARGE_POTION,
    HP_LARGE_POTION,
    HP_MEDIUM_POTION,
    HP_SMALL_POTION,
}

public enum AmbientType {
    LEVEL_AMBIENT
}

public enum UIType {
    BUTTON_CLICK,
    SELECT,
    SELECT2,
    OPEN_CRAFT,
    OPEN_SHOP,
    OPEN_CHEST,
    OPEN_ELEVATOR,
    USE_ELEVATOR,
    CRAFT,
    CHANGE_HELMET,
    BUY,
    UPGRADE,
    SWAP,
    EQUIP_HB,
    EQUIP_HP,
    DIALOG,
    SELECT_HELMET

}